version: '3.8'

services:
  jobsync:
    image: your-aws-account-id.dkr.ecr.your-aws-region.amazonaws.com/jobsync-repo:latest
    container_name: jobsync
    ports:
      - "8081:8081" 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/jobsync_db
      - SPRING_DATASOURCE_USERNAME=jobsync_user
      - SPRING_DATASOURCE_PASSWORD=jobsync_password
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=jobsync_user
      - POSTGRES_PASSWORD=jobsync_password
      - POSTGRES_DB=jobsync_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: